package Week45;

import java.util.Random;

/*
 * 12. Create a java program. 
 * Your program should have an array of booleans of length 10 
 * that will represent people’s opinion about a news they read on facebook. 
 * The data that will be inserted on the array 
 * will be generated by using the random.nextBoolean() method inside a for loop. 
 * After generating the values, print 
 * how many people believe that the news is real and 
 * print how many people thinks the new is a hoax.
 */

public class MathClass12 {

	public static void main(String[] args) {
		
		//array of booleans of length 10 to represent people’s opinion about a news
		Boolean[] boolArray = new Boolean[10];
		
		Random randomData = new Random();	//object of random class
		// random data generation
		// and storing data in array
		for( int i = 0; i <10; i++) {
			boolArray[i] = randomData.nextBoolean();
			System.out.println("Value at "+ i+ " is: "+ boolArray[i]);
			
			if(boolArray[i] == true) {
				System.out.println("News is Real");
			}else {
				System.out.println("News is a Hoax");
			}
		}
		

	}

}
