package Week45;

import java.util.Random;

/*
 * 13. Create a java program. 
 * Your program should print the result of the factorial of a randomly picked integer number 
 * between 0 and 10. The number should be generated by the class Random. 
 * You should also use a for loop. 
 * (Hint1: 0! = 1. Hint2: 1! = 1. Hint3: factorial of n; n! = 1*2*…*n-1*n. )
 */
public class MathClass13 {

	public static void main(String[] args) {
		
		
		// create a random class object
		Random random = new Random();
		
		// using random class to generate a random number between 0 and 10.
		int randomInteger = random.nextInt(10);
		System.out.println("Randomly picked integer is: "+ randomInteger);
		
		// Calculate factorial of that number
		int fact=1;
		for(int i =1; i <=randomInteger;i++) {
			fact = fact*i;
		}
		
		System.out.println("Factorial of " +randomInteger+ " is: " + fact);
	}

}
